.Dd August 12, 2022
.Dt HAXIP 1
.Sh NAME
.Nm haxip
.Nd gather information about players who join your haxball servers
.Sh SYNOPSIS
.Nm
.Op Fl Cfhn
.Op Fl c Ar count
.Op Fl I Ar interface
.Op Fl k Ar keeplog
.Sh OPTIONS
.Bl -tag -width indent
.It Fl C, -copy
copy the last ip to the clipboard
.It Fl f, -full
display ip, geolocation and timestamp
.It Fl h, -help
show usage
.It Fl n, -noheadings
do not display column headings
.It Fl c, -count
stop after displaying N entries
.It Fl i, -iface
set which network interface to sniff on
.It Fl k, -keeplog
discard ips included in the set of the last N ips logged
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It display full information & copy ip of last player/room
haxip -fCI $(ip route | awk '/default/ { print $5 }')
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/haxip/issues
