#!/bin/sh

count=-1
keeplog=-1
network_interface=''
opt_full=false
opt_noheadings=false
opt_copy=false

main() {
	parsed_args=$(getopt -o c:I:fk:nCh -l count:,iface:,keeplog:,full,noheadings,copy,help -n 'haxip' -- "$@")
	getopt_exit_code=$?
	captured_data_location=$(mktemp)
	
	[ $getopt_exit_code -ne 0 ] && exit 1

	eval set -- "$parsed_args"

	while :; do
		case "$1" in
			-k | --keeplog ) keeplog="$2"; shift 2 ;;
			-c | --count ) count="$2"; shift 2 ;;
			-I | --iface ) network_interface="$2"; shift 2 ;;
			-f | --full ) opt_full=true; shift 1 ;;
			-n | --noheadings ) opt_noheadings=true; shift 1 ;;
			-C | --copy ) opt_copy=true; shift 1 ;;
			-h | --help ) show_help; exit 1 ;; 
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	[ "$(id -u)" -ne 0 ] && die 'you must be root to execute this command'
	[ "$keeplog" -eq "$keeplog" ] 2>/dev/null || die 'keeplog must be a number'
	[ "$keeplog" -lt -1 ] && die 'keeplog must be equal or greater than -1'
	[ "$count" -eq "$count" ] 2>/dev/null || die 'count must be a number'
	[ "$count" -eq 0 ] && die 'count must be -1 or a positive integer'
	[ "$count" -lt -1 ] && die 'count must be -1 or a positive integer'
	[ -z "$network_interface" ] && die 'you must specify an interface'
	ip addr show "$network_interface" 2>/dev/null>&2 || die 'network interface does not exist'

	trap hinterrupt INT

	if ! $opt_noheadings; then
		if $opt_full; then
			show_full_header
		else
			show_short_header
		fi
	fi

	pending=$count

	while [ "$pending" -ne 0 ]; do
		[ "$pending" -ne -1 ] && pending=$((pending-1))
		ip=$(capture_unique)
		if $opt_full; then
			show_full_info "$ip"
		else
			show_short_info "$ip"
		fi

		if $opt_copy; then
			printf "%s" "$ip" | xclip -i -sel clipboard
		fi
	done

	[ -f "$captured_data_location" ] && rm "$captured_data_location"
}

show_help() {
	echo Usage: haxip [ -fnCh ] [ -k keeplog ] [ -c count ] [ -I interface ]
	echo Options are:
	echo '     -k | --keeplog                 discard ips included in the set of the last N ips logged'
	echo '     -c | --count                   stop after displaying N entries'
	echo '     -I | --iface                   set which network interface to sniff on'
	echo '     -f | --full                    display ip, geolocation and timestamp'
	echo '     -n | --noheadings              do not display column headings'
	echo '     -C | --copy                    copy the last ip to the clipboard'
	echo '     -h | --help                    display this message and exit'
}

die() {
	printf "haxip: %s\n" "$1" >&2
	exit 1
}

hinterrupt() {
	[ -f "$captured_data_location" ] && rm "$captured_data_location"
	exit 1
}

regexfmt() {
	read -r line;
	printf '(^%s' "$line";
	while read -r line; do
		printf '$)|(^%s' "$line"
	done;
	printf '$)\n'
}

capture() {
	ipv4s="$(ip -4 addr show "$network_interface" | grep -Eo 'inet (([0-9]+)\.){3}[0-9]+' | cut -d' ' -f2 | regexfmt)"
	ipv6s="$(ip -6 addr show "$network_interface" | grep -Eo 'inet6 ([a-f0-9]+:){7}[a-f0-9]+' | cut -d' ' -f2 | regexfmt)"

	while [ -z "$captured" ] ; do
		captured="$(tshark -i "$network_interface" -e ipv6.src -e ipv6.dst -e ip.src -e ip.dst -Tfields -Y 'dtls' -c1 2>/dev/null | tr '\t' '\n')"
	done

	echo "$captured" | grep -E -ve "(^$)|${ipv4s}|${ipv6s}"
}

capture_unique() {
	recent_capture=$(capture)

	while grep -iq "$recent_capture" "$captured_data_location"; do
		recent_capture=$(capture)
	done
	
	echo "$recent_capture" >> "$captured_data_location"

	if [ "$keeplog" -ne -1 ] ; then
		lines=$(tail -"$keeplog" "$captured_data_location")
		printf "%s\n" "$lines" > "$captured_data_location"
	fi

	echo "$recent_capture"
}

show_full_header() {
	printf "%-40s %-10s %-15s %-25s %-20s\n" IP CODE COUNTRY CITY TIMESTAMP
}

show_short_header() {
	printf "%-40s\n" IP
}

show_full_info() {
	ip="$1"

	ipdata="$(curl -s http://ip-api.com/json/"$ip")"
	country="$(echo "$ipdata" | jq '.country' | tr -d '"')"
	city="$(echo "$ipdata" | jq '.city' | tr -d '"')"
	code="$(echo "$ipdata" | jq '.countryCode' | tr -d '"')"
	timestamp="$(date +"%H:%M:%S")"

	printf "%-40s %-10s %-15s %-25s %-20s\n" "$ip" "$code" "$country" "$city" "$timestamp"
}

show_short_info() {
	ip="$1"
	printf "%s\n" "$ip"
}

main "$@"
